# Generated by Django 5.2 on 2025-04-30 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(help_text='Comma-separated keywords', max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('manuscript_file', models.FileField(upload_to='journals/')),
                ('supplementary_files', models.JSONField(blank=True, help_text='List of supplementary file names or URLs', null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revisions_required', 'Revisions Required'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=50)),
                ('co_authors', models.ManyToManyField(blank=True, related_name='coauthored_journals', to=settings.AUTH_USER_MODEL)),
                ('corresponding_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_journals', to=settings.AUTH_USER_MODEL)),
                ('journal_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.journalsection')),
                ('subject_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.subjectarea')),
            ],
        ),
    ]
