# Generated by Django 5.2 on 2025-06-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_journal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revisions_required', 'Revisions Required'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('review_done', 'Review Done'), ('assigned_to_area_editor', 'Assigned to Area Editor'), ('assigned_to_associate_editor', 'Assigned to Associate Editor')], default='submitted', max_length=50),
        ),
    ]
