# Generated by Django 5.2 on 2025-05-09 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0004_journal_author_name_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociateEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='ae_profile_pictures/')),
                ('institution', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('position_title', models.CharField(blank=True, max_length=255, null=True)),
                ('orcid_id', models.CharField(blank=True, max_length=50, null=True)),
                ('research_interests', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('subject_areas', models.ManyToManyField(blank=True, to='journal.subjectarea')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssociateEditorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('reviewing', 'Reviewing'), ('completed', 'Completed')], default='assigned', max_length=50)),
                ('associate_editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssociateEditor.associateeditor')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.journal')),
            ],
        ),
        migrations.CreateModel(
            name='AssociateEditorRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(choices=[('accept', 'Accept'), ('minor_revision', 'Minor Revision'), ('major_revision', 'Major Revision'), ('reject', 'Reject')], max_length=50)),
                ('justification', models.TextField(help_text='Why this decision was made')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('associate_editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssociateEditor.associateeditor')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.journal')),
            ],
        ),
    ]
