# Generated by Django 5.2 on 2025-05-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssociateEditor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associateeditor',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='associateeditor',
            name='editor_bio',
            field=models.TextField(blank=True, help_text='Brief biography for editorial board page', null=True),
        ),
        migrations.AddField(
            model_name='associateeditor',
            name='google_scholar_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associateeditor',
            name='language_proficiency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='associateeditor',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associateeditor',
            name='number_of_assignments_handled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='associateeditor',
            name='number_of_reviews_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='associateeditor',
            name='scopus_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='associateeditor',
            name='web_of_science_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
