# Generated by Django 5.2 on 2025-05-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssociateEditor', '0002_associateeditor_country_associateeditor_editor_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associateeditor',
            name='cv',
            field=models.FileField(blank=True, help_text='Upload the CV/resume of the Associate Editor.', null=True, upload_to='ae_cvs/'),
        ),
        migrations.AlterField(
            model_name='associateeditor',
            name='editor_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='associateeditor',
            name='number_of_assignments_handled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='associateeditor',
            name='number_of_reviews_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
