# Generated by Django 5.2 on 2025-05-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssociateEditor', '0003_associateeditor_cv_alter_associateeditor_editor_bio_and_more'),
        ('journal', '0004_journal_author_name_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='associateeditor',
            name='journal_sections',
            field=models.ManyToManyField(blank=True, to='journal.journalsection'),
        ),
    ]
