# Generated by Django 5.2 on 2025-05-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssociateEditor', '0004_associateeditor_journal_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='associateeditorrecommendation',
            name='overall_rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='associateeditorrecommendation',
            name='public_comments_to_author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associateeditorrecommendation',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='associateeditorrecommendation',
            name='justification',
            field=models.TextField(help_text='Detailed reasoning behind the recommendation.'),
        ),
    ]
