# Generated by Django 5.2 on 2025-05-13 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0004_journal_author_name_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='area_editor_profiles/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='area_editor_cvs/')),
                ('institution', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('position_title', models.CharField(blank=True, max_length=255, null=True)),
                ('orcid_id', models.CharField(blank=True, max_length=50, null=True)),
                ('research_interests', models.TextField(blank=True, null=True)),
                ('editor_bio', models.TextField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('google_scholar_profile', models.URLField(blank=True, null=True)),
                ('scopus_id', models.CharField(blank=True, max_length=100, null=True)),
                ('web_of_science_id', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('language_proficiency', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_assignments_handled', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('journal_sections', models.ManyToManyField(blank=True, to='journal.journalsection')),
                ('subject_areas', models.ManyToManyField(blank=True, to='journal.subjectarea')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
