# Generated by Django 5.2 on 2025-05-13 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AreaEditor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDetailOfAreaEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=255)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('grade_or_score', models.CharField(blank=True, max_length=50, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='area_editor_certificates/')),
                ('area_editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='AreaEditor.areaeditor')),
            ],
        ),
    ]
