# Generated by Django 5.2 on 2025-05-15 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AreaEditor', '0002_educationdetailofareaeditor'),
        ('journal', '0004_journal_author_name_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetailofareaeditor',
            name='end_year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='educationdetailofareaeditor',
            name='start_year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='AreaEditorJournalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='assigned', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('area_editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AreaEditor.areaeditor')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.journal')),
            ],
        ),
    ]
