# Generated by Django 5.2 on 2025-05-16 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AreaEditor', '0003_alter_educationdetailofareaeditor_end_year_and_more'),
        ('journal', '0004_journal_author_name_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEditorRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(choices=[('accept', 'Accept'), ('minor_revision', 'Minor Revision'), ('major_revision', 'Major Revision'), ('reject', 'Reject')], max_length=20)),
                ('summary', models.TextField()),
                ('overall_rating', models.PositiveSmallIntegerField()),
                ('justification', models.TextField()),
                ('public_comments_to_author', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('area_editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AreaEditor.areaeditor')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.journal')),
            ],
            options={
                'unique_together': {('journal', 'area_editor')},
            },
        ),
    ]
