# Generated by Django 5.2 on 2025-05-02 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_deletionotp'),
        ('reviewer', '0002_reviewerassignmenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('rating', models.PositiveIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=3)),
                ('confidential_comments', models.TextField(blank=True, help_text="Comments to the editor that won't be shown to the author.", null=True)),
                ('recommendation', models.CharField(choices=[('accept', 'Accept'), ('minor_revision', 'Minor Revision'), ('major_revision', 'Major Revision'), ('reject', 'Reject')], help_text='Overall recommendation regarding the manuscript.', max_length=50)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_upload', models.FileField(blank=True, help_text='Optional file (e.g., annotated manuscript or comments).', null=True, upload_to='review_feedback_files/')),
                ('is_final_submission', models.BooleanField(default=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.journal')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewer.reviewer')),
            ],
        ),
    ]
