# Generated by Django 5.2 on 2025-05-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0003_reviewfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetailofreviewer',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationdetailofreviewer',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
