# Generated by Django 5.2 on 2025-05-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0004_alter_educationdetailofreviewer_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetailofreviewer',
            name='end_year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='educationdetailofreviewer',
            name='start_year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
