# Generated by Django 5.2 on 2025-05-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Editor_Chief', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorinchief',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
