# Generated by Django 5.2 on 2025-06-03 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Editor_Chief', '0002_editorinchief_is_approved'),
        ('journal', '0005_alter_journal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorInChiefRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(choices=[('accept', 'Accept'), ('minor_revision', 'Minor Revision'), ('major_revision', 'Major Revision'), ('reject', 'Reject'), ('pending', 'Pending Review')], default='pending', max_length=20)),
                ('decision_summary', models.TextField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, null=True)),
                ('decision_date', models.DateTimeField(auto_now_add=True)),
                ('requires_review', models.BooleanField(default=False)),
                ('review_deadline', models.DateField(blank=True, null=True)),
                ('is_final_decision', models.BooleanField(default=False)),
                ('editor_in_chief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Editor_Chief.editorinchief')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eic_recommendations', to='journal.journal')),
            ],
            options={
                'ordering': ['-decision_date'],
                'unique_together': {('journal', 'editor_in_chief')},
            },
        ),
        migrations.CreateModel(
            name='EditorInChiefFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='Editor_Chief.editorinchiefrecommendation')),
            ],
        ),
    ]
